remote_theme: jekyll/minima

minima:
  skin: solarized
  social_links:
    - title: github
      icon: github
      url: "https://github.com/jyzhu-pointless"
    - title: email
      icon: email
      url: "mailto:jyzhu_2020@stu.pku.edu.cn"

plugins:
- jekyll-remote-theme

title: Jinyu Zhu

# Timezone for rendering post dates on GitHub Pages (set to China Standard Time)
timezone: Asia/Shanghai

header_pages:
- index.md
- posts/index.md
- gene-drive-playground.html
- friends/index.md

author: 
  name: Jinyu Zhu
  email: jyzhu_2020@stu.pku.edu.cn
  url: https://jyzhu-pointless.github.io/

kramdown:
  math_engine: MathJax

description: Personal homepage for Jinyu Zhu
